<!DOCTYPE html>
<html lang="zh-TW" >
  <head><meta name="generator" content="Hexo 3.8.0">
  <meta charset="utf-8">
  
  <title>Ruby 中該如何 Raise 一個錯誤 | 弦而時習之</title>
  <meta name="theme-color" content="#EFEFEF">

  <meta name="author" content="蒼時弦也">
  
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="description" content="前幾天的晚上朋友在 Facebook 上問了一個問題。 1raise HTTPError, &apos;Not Found&apos; 和 1raise HTTPError.new(&apos;Not Found&apos;) 哪個比較快？也因為這樣，我們意外的發現 Ruby 對上面兩段程式碼的定義上其實是不太一樣的。">
<meta name="keywords" content="Ruby,筆記">
<meta property="og:type" content="article">
<meta property="og:title" content="Ruby 中該如何 Raise 一個錯誤">
<meta property="og:url" content="https://blog.frost.tw/posts/2018/01/09/How-ruby-raise-an-error/">
<meta property="og:site_name" content="弦而時習之">
<meta property="og:description" content="前幾天的晚上朋友在 Facebook 上問了一個問題。 1raise HTTPError, &apos;Not Found&apos; 和 1raise HTTPError.new(&apos;Not Found&apos;) 哪個比較快？也因為這樣，我們意外的發現 Ruby 對上面兩段程式碼的定義上其實是不太一樣的。">
<meta property="og:locale" content="zh-TW">
<meta property="og:image" content="http://blog.frost.tw/icon-512.png">
<meta property="og:updated_time" content="2018-03-15T03:00:35.000Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Ruby 中該如何 Raise 一個錯誤">
<meta name="twitter:description" content="前幾天的晚上朋友在 Facebook 上問了一個問題。 1raise HTTPError, &apos;Not Found&apos; 和 1raise HTTPError.new(&apos;Not Found&apos;) 哪個比較快？也因為這樣，我們意外的發現 Ruby 對上面兩段程式碼的定義上其實是不太一樣的。">
<meta name="twitter:image" content="http://blog.frost.tw/icon-512.png">
<link rel="publisher" href="https://plus.google.com/117236344655673213049">
<meta property="fb:app_id" content="178355449110">

  <meta property="fb:pages" content="180666522388">
  <script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Blog",
    "name": "弦而時習之",
    "url": "https://blog.frost.tw",
    "image": "http://blog.frost.tw/icon-512.png",
    "description": "蒼時弦也的個人網誌，專注在前端、後端以及遊戲開發，大多使用 Ruby 和 Ruby on Rails 以及 Golang、JS 和 C 語言。",
    "sameAs": [
      "https://www.facebook.com/frost.tw/"
    ]
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Person",
    "name": "蒼時弦也",
    "url": "https://blog.frost.tw",
    "sameAs": [
      "https://www.facebook.com/elct9620",
      "https://www.instagram.com/elct9620/",
      "https://twitter.com/elct9620",
      "https://plus.google.com/+%E8%92%BC%E6%99%82%E5%BC%A6%E4%B9%9F-plus",
      "https://www.linkedin.com/in/elct9620"
    ]
}
</script>


<script type="application/ld+json">
{
  "@context":"http://schema.org",
  "@type":"Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://blog.frost.tw/posts/2018/01/09/How-ruby-raise-an-error/"
  },
  "headline":"Ruby 中該如何 Raise 一個錯誤",
  "image": [
    
    "http://blog.frost.tw/icon-512.png"
  ],
  "datePublished": "2018-01-09T09:28:13.000Z",
  "dateModified": "2018-03-15T03:00:35.000Z",
  "description":"前幾天的晚上朋友在 Facebook 上問了一個問題。1raise HTTPError, 'Not Found'和1raise HTTPError.new('Not Found')哪個比較快？也因為這樣，我們意外的發現 Ruby 對上面兩段程式碼的定義上其實是不太一樣的。",
  "author": {
    "@type": "Person",
    "name": "蒼時弦也"
  },
  "publisher": {
    "@type": "Organization",
    "name": "蒼時弦也",
    "logo": {
      "@type": "ImageObject",
      "url": "http://blog.forst.tw/logo-wide.png"
    }
  }
}
</script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "item": {
      "@id": "https://blog.frost.tw",
      "name": "弦而時習之 ",
      "image": "http://blog.frost.tw/icon-512.png"
    }
  },{
    "@type": "ListItem",
    "position": 2,
    "item": {
      "@id": "https://blog.frost.tw/posts/2018/01/09/How-ruby-raise-an-error/",
      "name": "Ruby 中該如何 Raise 一個錯誤",
      "image": "http://blog.frost.tw/icon-512.png"
    }
  }]
}
</script>




  
  <link rel="canonical" href="https://blog.frost.tw/posts/2018/01/09/How-ruby-raise-an-error/">
  
  <link href="/icon-512.png" rel="icon">
  <link rel="alternate" href="/feed.xml" title="弦而時習之" type="application/rss+xml">
  <!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

  <link rel="stylesheet" href="/css/style.css" media="screen" type="text/css">
  <script async src="/js/turbolinks.js"></script>
</head>

  <body>
    <div id="fb-root" data-turbolinks-permanent></div>
    <header id="header">
      
<h1 id="sitename">
  <a href="/" class="hide-text logo--icon align-center">
  弦而時習之
  </a>
</h1>

<aside id="slogan" class="slogan align-center text-center">
  <h2 class="slogan__title">Aotokitsuruya</h2>
  <p class="slogan__description">The Web is attracting  me, so I start learning PHP, HTML, CSS and JavaScript. When I know about Ruby, I fall in love with it. Now, I working with my friend to design games using C++ and still learning web about Golang, Ruby and JavaScript. In the other side, I also be a designer, the reason why the web is attracted me.</p>
</aside>

    </header>
    <div id="wrapper">
      
<article class="post article">
  <header class="article__header">
    <time datetime="2018-01-09T09:28:13.000Z" class="article__time--header">
      Jan.09
    </time>
    
  
    <h1 class="article__title">Ruby 中該如何 Raise 一個錯誤</h1>
  


  </header>
  <div class="article__entry">
    
    <p>前幾天的晚上朋友在 Facebook 上問了一個問題。</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">raise HTTPError, <span class="string">'Not Found'</span></span><br></pre></td></tr></table></figure>
<p>和</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">raise HTTPError.new(<span class="string">'Not Found'</span>)</span><br></pre></td></tr></table></figure>
<p>哪個比較快？也因為這樣，我們意外的發現 Ruby 對上面兩段程式碼的定義上其實是不太一樣的。</p>
<a id="more"></a>
<p>在 Ruby 中 <code>raise</code> 一般情況下有以下幾種運作方式。</p>
<h2 id="預設情況"><a href="#預設情況" class="headerlink" title="預設情況"></a>預設情況</h2><figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># Case 1</span></span><br><span class="line">raise <span class="comment"># =&gt; #&lt;RuntimeError&gt;</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># Case 2</span></span><br><span class="line">raise <span class="string">'NotFound'</span> <span class="comment"># =&gt; #&lt;RuntimeError: "Not Found"&gt;</span></span><br></pre></td></tr></table></figure>
<h2 id="一般用法"><a href="#一般用法" class="headerlink" title="一般用法"></a>一般用法</h2><figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># Case 3</span></span><br><span class="line">raise HTTPError, <span class="string">'Not Found'</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># Case 4</span></span><br><span class="line">raise HTTPError.new(<span class="string">'Not Found'</span>)</span><br></pre></td></tr></table></figure>
<p>不過，上面這兩段程式碼的差異在哪裡呢？從 Ruby 的原始碼可以看到 <code>.new</code> 的行為會多做一次檢查。</p>
<figure class="highlight c"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">static</span> VALUE</span><br><span class="line">make_exception(<span class="keyword">int</span> argc, <span class="keyword">const</span> VALUE *argv, <span class="keyword">int</span> isstr)</span><br><span class="line">&#123;</span><br><span class="line">    VALUE mesg, exc;</span><br><span class="line">    <span class="keyword">int</span> n;</span><br><span class="line"></span><br><span class="line">    mesg = Qnil;</span><br><span class="line">    <span class="keyword">switch</span> (argc) &#123;</span><br><span class="line">      <span class="keyword">case</span> <span class="number">0</span>:</span><br><span class="line">        <span class="keyword">break</span>;</span><br><span class="line">      <span class="keyword">case</span> <span class="number">1</span>:</span><br><span class="line">        exc = argv[<span class="number">0</span>];</span><br><span class="line">        <span class="keyword">if</span> (NIL_P(exc))</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        <span class="comment">// 檢查了是否為字串</span></span><br><span class="line">        <span class="keyword">if</span> (isstr) &#123;</span><br><span class="line">            mesg = rb_check_string_type(exc);</span><br><span class="line">            <span class="keyword">if</span> (!NIL_P(mesg)) &#123;</span><br><span class="line">                mesg = rb_exc_new3(rb_eRuntimeError, mesg);</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">        n = <span class="number">0</span>;</span><br><span class="line">        <span class="comment">// 繼續跟 raise HTTPError, 'Not Fonud' 一樣的行為</span></span><br><span class="line">        <span class="keyword">goto</span> exception_call;</span><br><span class="line"></span><br><span class="line">      <span class="keyword">case</span> <span class="number">2</span>:</span><br><span class="line">      <span class="keyword">case</span> <span class="number">3</span>:</span><br><span class="line">        exc = argv[<span class="number">0</span>];</span><br><span class="line">        n = <span class="number">1</span>;</span><br><span class="line">      exception_call:</span><br><span class="line">        mesg = rb_check_funcall(exc, idException, n, argv+<span class="number">1</span>);</span><br><span class="line">        <span class="keyword">if</span> (mesg == Qundef) &#123;</span><br><span class="line">            rb_raise(rb_eTypeError, <span class="string">"exception class/object expected"</span>);</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">break</span>;</span><br><span class="line">      <span class="keyword">default</span>:</span><br><span class="line">        rb_check_arity(argc, <span class="number">0</span>, <span class="number">3</span>);</span><br><span class="line">        <span class="keyword">break</span>;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">if</span> (argc &gt; <span class="number">0</span>) &#123;</span><br><span class="line">        <span class="keyword">if</span> (!rb_obj_is_kind_of(mesg, rb_eException))</span><br><span class="line">            rb_raise(rb_eTypeError, <span class="string">"exception object expected"</span>);</span><br><span class="line">        <span class="keyword">if</span> (argc &gt; <span class="number">2</span>)</span><br><span class="line">            set_backtrace(mesg, argv[<span class="number">2</span>]);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> mesg;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>從這個角度看，我們會發現差異其實只是「多一次檢查」的程度，甚至不太影響運行的效能。不過從 <a href="ruby-doc.com/docs/ProgrammingRuby/html/tut_exceptions.html">Programming Ruby</a> 這本書中的範例，卻發現了一個稍微意想不到的使用方法。</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">readData</span><span class="params">(socket)</span></span></span><br><span class="line">  data = socket.read(<span class="number">512</span>)</span><br><span class="line">  <span class="keyword">if</span> data.<span class="literal">nil</span>?</span><br><span class="line">    raise RetryException.new(<span class="literal">true</span>), <span class="string">"transient read error"</span></span><br><span class="line">  <span class="keyword">end</span></span><br><span class="line">  <span class="comment"># .. normal processing</span></span><br><span class="line"><span class="keyword">end</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># ...</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">begin</span></span><br><span class="line">  stuff = readData(socket)</span><br><span class="line">  <span class="comment"># .. process stuff</span></span><br><span class="line"><span class="keyword">rescue</span> RetryException =&gt; detail</span><br><span class="line">  <span class="keyword">retry</span> <span class="keyword">if</span> detail.okToRetry</span><br><span class="line">  raise</span><br><span class="line"><span class="keyword">end</span></span><br></pre></td></tr></table></figure>
<p>仔細一看，明明應該是 <code>@message</code> 的數值，被放入了非字串的數值，而且這個錯誤還提供了 <code>#okToRetry</code> 這樣的方法讓我們可以獲取到這個數值。</p>
<p>回到剛剛 Ruby 中 <code>make_exception</code> 的原始碼，在 2 ~ 3 個參數的情況下，回傳的 <code>mesg</code> 變數是透過呼叫一個透過 <code>idException</code> 指標定義的方法來產生的，而傳入的參數剛好是 <code>raise</code> 的第二個參數。</p>
<figure class="highlight c"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">case</span> <span class="number">2</span>:</span><br><span class="line"> <span class="keyword">case</span> <span class="number">3</span>:</span><br><span class="line">   exc = argv[<span class="number">0</span>];</span><br><span class="line">   n = <span class="number">1</span>;</span><br><span class="line"> exception_call:</span><br><span class="line">   mesg = rb_check_funcall(exc, idException, n, argv+<span class="number">1</span>); <span class="comment">// 呼叫 idException 指標對應的某個方法</span></span><br><span class="line">   <span class="keyword">if</span> (mesg == Qundef) &#123;</span><br><span class="line">       rb_raise(rb_eTypeError, <span class="string">"exception class/object expected"</span>);</span><br><span class="line">   &#125;</span><br><span class="line">   <span class="keyword">break</span>;</span><br></pre></td></tr></table></figure>
<blockquote>
<p><code>idException</code> 對應的其實是呼叫物件上的 <code>#exception</code> 方法，是所有 <code>Error</code> 類型物件必須存在的方法。</p>
</blockquote>
<p>也就是說，實際上我們可以讓我們的 <code>Error</code> 附帶一些額外資訊，在一些情況下處理錯誤的時候可以用來輔助我們。</p>
<p>不過，既然第一個參數已經被我們自訂的錯誤資訊替換了，那麼 Ruby 是怎麼設定錯誤訊息的？</p>
<p>實際上，在 <code>idException</code> 對應的 <code>#exception</code> 方法上，會複製現有的物件，件並且把錯誤訊息放進去。</p>
<p>在 <code>#exception</code> 的原始碼是這樣實作的。</p>
<figure class="highlight c"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">static</span> VALUE</span><br><span class="line">exc_exception(<span class="keyword">int</span> argc, VALUE *argv, VALUE self)</span><br><span class="line">&#123;</span><br><span class="line">    VALUE exc;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (argc == <span class="number">0</span>) <span class="keyword">return</span> self;</span><br><span class="line">    <span class="keyword">if</span> (argc == <span class="number">1</span> &amp;&amp; self == argv[<span class="number">0</span>]) <span class="keyword">return</span> self;</span><br><span class="line">    exc = rb_obj_clone(self);</span><br><span class="line">    exc_initialize(argc, argv, exc);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> exc;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<figure class="highlight c"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">static</span> VALUE</span><br><span class="line">exc_initialize(<span class="keyword">int</span> argc, VALUE *argv, VALUE exc)</span><br><span class="line">&#123;</span><br><span class="line">    VALUE arg;</span><br><span class="line"></span><br><span class="line">    rb_scan_args(argc, argv, <span class="string">"01"</span>, &amp;arg);</span><br><span class="line">    rb_ivar_set(exc, id_mesg, arg);</span><br><span class="line">    rb_ivar_set(exc, id_bt, Qnil);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> exc;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>也就是說，我們實際上 <code>raise</code> 出來的例外，其實是被重新修改過的，不過這也讓我們在使用 Ruby 的錯誤上可以更加的彈性。</p>
<p>這也是為什麼像是 Rubocop 之類的軟體，會建議使用下面這種方式產生錯誤的原因。</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">raise NotFoundError</span><br><span class="line"></span><br><span class="line">raise NotFoundError, <span class="string">'Current page is unavailable'</span></span><br></pre></td></tr></table></figure>
<blockquote>
<p>關於 <code>#exception</code> 的部分感謝五倍的同事在討論的時候提出來，才發現還有後續的處理將 <code>#message</code> 設定上去。</p>
</blockquote>

    
    <footer class="article__footer">
      
        <div class="text-center">
          <div class="fb-share-button" data-href="https://blog.frost.tw/posts/2018/01/09/How-ruby-raise-an-error/" data-layout="button_count">
          </div>
        </div>
        <p align="center">
          <a href="https://ko-fi.com/J3J78093" target="_blank">
            <img height="36" style="border:0px;height:36px;" src="https://az743702.vo.msecnd.net/cdn/kofi5.png?v=0" border="0" alt="Buy Me a Coffee at ko-fi.com">
          </a>
        </p>
        <iframe scrolling="no" frameborder="0" style="display: block; margin: 0 auto; height: 212px;" src="https://button.like.co/in/embed/elct9620/button?referrer=https://blog.frost.tw/posts/2018/01/09/How-ruby-raise-an-error/"></iframe>
        
          <ul class="article__tag-list"><li class="article__tag-list-item"><a class="article__tag-list-link" href="/tags/Ruby/">Ruby</a></li><li class="article__tag-list-item"><a class="article__tag-list-link" href="/tags/筆記/">筆記</a></li></ul>
        
      
    </footer>
  </div>
</article>


  
    <div class="adv">
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <!-- 網誌_文末廣告 (Hexo) -->
      <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2844969736316510" data-ad-slot="5530952976" data-ad-format="auto"></ins>
      <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
    </div>
  

  
<section id="comment" class="comment-box">
  <h1 class="comment-box__title">留言</h1>

  <div id="disqus_thread">
    <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  </div>
</section>






    </div>
    <footer id="footer">
      <div id="copyright">
  &copy;2013 <a href="https://plus.google.com/117236344655673213049?rel=author" target="_blank">蒼時弦也</a>. All right reversed.
</div>

    </footer>
    

  <script type="text/javascript">
  window.disqus_shortname = 'revo-skill-frost';

  
  (function(){
    var dsq = document.createElement('script');
    dsq.type = 'text/javascript';
    dsq.async = true;
    dsq.src = '//' + window.disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  }());
  
  </script>

  
  <!-- Google Tag Manager -->
  <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-5TQLRN" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-5TQLRN');</script>
  <!-- End Google Tag Manager -->
  

  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '178355449110',
        xfbml      : true,
        version    : 'v2.12'
      });

      FB.AppEvents.logPageView();

    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "https://connect.facebook.net/zh_TW/sdk.js";
       js.async = true
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  </script>

  <script src="/js/app.js"></script>


    <div class="loading"></div>
  </body>
</html>
